apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: model-server
    app: model-server
  name: model-server
  namespace: nova
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: model-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: model-server
    spec:
      containers:
        - image: krisnova/modelserver
          imagePullPolicy: Always
          name: model-server
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 777
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: model-server
  name: model-server
  namespace: nova
spec:
  ports:
    - port: 777
      protocol: TCP
      targetPort: 777
  selector:
    run: model-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
