// Code generated by protoc-gen-go. DO NOT EDIT.
// source: processor/processor.proto

package suggester

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCommentRequest struct {
	PullRequestURL       string   `protobuf:"bytes,1,opt,name=pullRequestURL,proto3" json:"pullRequestURL,omitempty"`
	PullRequestPatchURL  string   `protobuf:"bytes,2,opt,name=pullRequestPatchURL,proto3" json:"pullRequestPatchURL,omitempty"`
	RepoName             string   `protobuf:"bytes,3,opt,name=repoName,proto3" json:"repoName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentRequest) Reset()         { *m = GetCommentRequest{} }
func (m *GetCommentRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentRequest) ProtoMessage()    {}
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dba5aea5cd8f1899, []int{0}
}

func (m *GetCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentRequest.Unmarshal(m, b)
}
func (m *GetCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentRequest.Marshal(b, m, deterministic)
}
func (m *GetCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentRequest.Merge(m, src)
}
func (m *GetCommentRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentRequest.Size(m)
}
func (m *GetCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentRequest proto.InternalMessageInfo

func (m *GetCommentRequest) GetPullRequestURL() string {
	if m != nil {
		return m.PullRequestURL
	}
	return ""
}

func (m *GetCommentRequest) GetPullRequestPatchURL() string {
	if m != nil {
		return m.PullRequestPatchURL
	}
	return ""
}

func (m *GetCommentRequest) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

type GetCommentResponse struct {
	PullRequestURL       string              `protobuf:"bytes,1,opt,name=pullRequestURL,proto3" json:"pullRequestURL,omitempty"`
	FileNameLinePairs    []*FileNameLinePair `protobuf:"bytes,2,rep,name=fileNameLinePairs,proto3" json:"fileNameLinePairs,omitempty"`
	Message              string              `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetCommentResponse) Reset()         { *m = GetCommentResponse{} }
func (m *GetCommentResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommentResponse) ProtoMessage()    {}
func (*GetCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dba5aea5cd8f1899, []int{1}
}

func (m *GetCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentResponse.Unmarshal(m, b)
}
func (m *GetCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentResponse.Marshal(b, m, deterministic)
}
func (m *GetCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentResponse.Merge(m, src)
}
func (m *GetCommentResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommentResponse.Size(m)
}
func (m *GetCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentResponse proto.InternalMessageInfo

func (m *GetCommentResponse) GetPullRequestURL() string {
	if m != nil {
		return m.PullRequestURL
	}
	return ""
}

func (m *GetCommentResponse) GetFileNameLinePairs() []*FileNameLinePair {
	if m != nil {
		return m.FileNameLinePairs
	}
	return nil
}

func (m *GetCommentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FileNameLinePair struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	LineNumber           int32    `protobuf:"varint,2,opt,name=lineNumber,proto3" json:"lineNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileNameLinePair) Reset()         { *m = FileNameLinePair{} }
func (m *FileNameLinePair) String() string { return proto.CompactTextString(m) }
func (*FileNameLinePair) ProtoMessage()    {}
func (*FileNameLinePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_dba5aea5cd8f1899, []int{2}
}

func (m *FileNameLinePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileNameLinePair.Unmarshal(m, b)
}
func (m *FileNameLinePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileNameLinePair.Marshal(b, m, deterministic)
}
func (m *FileNameLinePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileNameLinePair.Merge(m, src)
}
func (m *FileNameLinePair) XXX_Size() int {
	return xxx_messageInfo_FileNameLinePair.Size(m)
}
func (m *FileNameLinePair) XXX_DiscardUnknown() {
	xxx_messageInfo_FileNameLinePair.DiscardUnknown(m)
}

var xxx_messageInfo_FileNameLinePair proto.InternalMessageInfo

func (m *FileNameLinePair) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileNameLinePair) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*GetCommentRequest)(nil), "processor.service.GetCommentRequest")
	proto.RegisterType((*GetCommentResponse)(nil), "processor.service.GetCommentResponse")
	proto.RegisterType((*FileNameLinePair)(nil), "processor.service.FileNameLinePair")
}

func init() { proto.RegisterFile("processor/processor.proto", fileDescriptor_dba5aea5cd8f1899) }

var fileDescriptor_dba5aea5cd8f1899 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0xc4, 0xad, 0x78, 0x74, 0x41, 0x40, 0xcd, 0x25, 0xf4, 0x80, 0xaa, 0xf0, 0x50, 0x2f, 0x35,
	0xa8, 0xf0, 0x05, 0x45, 0x02, 0x0e, 0xa5, 0x0a, 0x41, 0x70, 0x80, 0x53, 0x9a, 0x2e, 0xa9, 0xd5,
	0x38, 0x36, 0xb6, 0xc3, 0x3f, 0xf0, 0x29, 0xfc, 0x25, 0x4a, 0xda, 0xa4, 0x55, 0x53, 0x09, 0x6e,
	0x3b, 0xe3, 0xd9, 0xd5, 0xec, 0x7a, 0xe0, 0xd8, 0xa4, 0x51, 0x84, 0xc6, 0xa2, 0xbe, 0x2c, 0x2b,
	0xa6, 0xb4, 0xb4, 0x92, 0x36, 0x17, 0x84, 0x41, 0xfd, 0xc5, 0x43, 0x74, 0xbf, 0x09, 0x34, 0xef,
	0xd1, 0xde, 0x4a, 0x21, 0x30, 0xb1, 0x3e, 0x7e, 0xa6, 0x68, 0x2c, 0xbd, 0x80, 0x7d, 0x95, 0xc6,
	0xf1, 0x1c, 0xbe, 0xf8, 0x03, 0x87, 0xb4, 0x49, 0xa7, 0xe1, 0xaf, 0xb0, 0xf4, 0x0a, 0x8e, 0x96,
	0x18, 0x2f, 0xb0, 0xe1, 0x24, 0x13, 0xd7, 0x72, 0xf1, 0xba, 0x27, 0xda, 0x82, 0x1d, 0x8d, 0x4a,
	0x0e, 0x03, 0x81, 0x4e, 0x3d, 0x97, 0x95, 0xd8, 0xfd, 0x21, 0x40, 0x97, 0xbd, 0x18, 0x25, 0x13,
	0x83, 0xff, 0x36, 0xf3, 0x04, 0xcd, 0x0f, 0x1e, 0x63, 0x36, 0x6a, 0xc0, 0x13, 0xf4, 0x02, 0xae,
	0x8d, 0x53, 0x6b, 0xd7, 0x3b, 0xbb, 0xbd, 0x53, 0x56, 0xd9, 0x9c, 0xdd, 0xad, 0x68, 0xfd, 0x6a,
	0x37, 0x75, 0x60, 0x5b, 0xa0, 0x31, 0x41, 0x54, 0x98, 0x2d, 0xa0, 0x3b, 0x84, 0xc3, 0xd5, 0x01,
	0xd9, 0x6e, 0xc5, 0x88, 0xb9, 0xc5, 0x12, 0xd3, 0x13, 0x80, 0x98, 0x27, 0x38, 0x4c, 0xc5, 0x08,
	0x75, 0x7e, 0xa0, 0x4d, 0x7f, 0x89, 0xe9, 0x4d, 0x61, 0xef, 0x51, 0x8e, 0xb1, 0xd8, 0x87, 0xbe,
	0x03, 0x2c, 0x4e, 0x41, 0xcf, 0xd6, 0xf8, 0xaf, 0xfc, 0x5a, 0xeb, 0xfc, 0x0f, 0xd5, 0xec, 0x9e,
	0xee, 0x46, 0xff, 0x15, 0x6e, 0x42, 0x29, 0x58, 0xc4, 0xed, 0x24, 0x1d, 0xb1, 0xac, 0x9c, 0xc8,
	0x78, 0x8c, 0xc9, 0x94, 0x29, 0x8d, 0x63, 0x1e, 0xda, 0xae, 0xd2, 0xdd, 0x70, 0xd6, 0x66, 0x16,
	0x29, 0xea, 0x1f, 0x3c, 0x17, 0xa5, 0x97, 0xe5, 0xc9, 0x3c, 0x10, 0x8f, 0xbc, 0x35, 0xca, 0xf7,
	0xd1, 0x56, 0x1e, 0xb3, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x0f, 0x88, 0x53, 0x83,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModelRequestClient is the client API for ModelRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModelRequestClient interface {
	GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error)
}

type modelRequestClient struct {
	cc *grpc.ClientConn
}

func NewModelRequestClient(cc *grpc.ClientConn) ModelRequestClient {
	return &modelRequestClient{cc}
}

func (c *modelRequestClient) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error) {
	out := new(GetCommentResponse)
	err := c.cc.Invoke(ctx, "/processor.service.ModelRequest/GetComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelRequestServer is the server API for ModelRequest service.
type ModelRequestServer interface {
	GetComment(context.Context, *GetCommentRequest) (*GetCommentResponse, error)
}

func RegisterModelRequestServer(s *grpc.Server, srv ModelRequestServer) {
	s.RegisterService(&_ModelRequest_serviceDesc, srv)
}

func _ModelRequest_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelRequestServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processor.service.ModelRequest/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelRequestServer).GetComment(ctx, req.(*GetCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModelRequest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "processor.service.ModelRequest",
	HandlerType: (*ModelRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetComment",
			Handler:    _ModelRequest_GetComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "processor/processor.proto",
}
